SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS `stock_flow` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE `stock_flow`;

-- ----------------------------
-- Table structure for sys_users
-- ----------------------------
DROP TABLE IF EXISTS `sys_users`;
CREATE TABLE IF NOT EXISTS `sys_users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `password_hash` varchar(255) NOT NULL COMMENT '密码哈希值',
  `real_name` varchar(50) DEFAULT NULL COMMENT '真实姓名',
  `role` varchar(20) NOT NULL COMMENT '角色: Admin, Keeper, User',
  `status` tinyint DEFAULT 1 COMMENT '状态: 1正常, 0禁用',
  `created_at` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime(3) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_sys_users_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- ----------------------------
-- Table structure for wms_materials
-- ----------------------------
DROP TABLE IF EXISTS `wms_materials`;
CREATE TABLE IF NOT EXISTS `wms_materials` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `code` varchar(50) NOT NULL COMMENT '物料编码',
  `name` varchar(100) NOT NULL COMMENT '物料名称',
  `category` varchar(50) DEFAULT NULL COMMENT '分类',
  `spec` varchar(50) DEFAULT NULL COMMENT '规格',
  `unit` varchar(20) DEFAULT NULL COMMENT '单位',
  `brand` varchar(50) DEFAULT NULL COMMENT '品牌',
  `created_at` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime(3) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_wms_materials_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='耗材基础信息表';

-- ----------------------------
-- Table structure for wms_inventory
-- ----------------------------
DROP TABLE IF EXISTS `wms_inventory`;
CREATE TABLE IF NOT EXISTS `wms_inventory` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `material_id` bigint unsigned NOT NULL COMMENT '关联物料ID',
  `batch_no` varchar(50) NOT NULL COMMENT '内部批号',
  `inbound_no` varchar(50) NOT NULL COMMENT '入库单号',
  `initial_qty` bigint NOT NULL COMMENT '初始入库数量',
  `current_qty` bigint NOT NULL COMMENT '当前剩余数量',
  `expiry_date` date DEFAULT NULL COMMENT '有效期',
  `created_at` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime(3) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_wms_inventory_inbound_no` (`inbound_no`),
  KEY `idx_wms_inventory_material_id` (`material_id`),
  KEY `idx_wms_inventory_expiry_date` (`expiry_date`),
  CONSTRAINT `fk_wms_inventory_material` FOREIGN KEY (`material_id`) REFERENCES `wms_materials` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存批次表';

-- ----------------------------
-- Table structure for wms_outbound
-- ----------------------------
DROP TABLE IF EXISTS `wms_outbound`;
CREATE TABLE IF NOT EXISTS `wms_outbound` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `outbound_no` varchar(50) NOT NULL COMMENT '领出单号',
  `inventory_id` bigint unsigned NOT NULL COMMENT '关联库存ID',
  `user_id` bigint unsigned NOT NULL COMMENT '领用人ID',
  `quantity` bigint NOT NULL COMMENT '领出数量',
  `purpose` varchar(255) DEFAULT NULL COMMENT '领用用途',
  `status` varchar(20) DEFAULT 'USING' COMMENT '状态: USING(使用中), FINISHED(已用完)',
  `snap_expiry_date` date DEFAULT NULL COMMENT '快照有效期',
  `apply_date` datetime(3) DEFAULT NULL COMMENT '申请时间',
  `created_at` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime(3) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_wms_outbound_outbound_no` (`outbound_no`),
  KEY `idx_wms_outbound_inventory_id` (`inventory_id`),
  KEY `idx_wms_outbound_user_id` (`user_id`),
  CONSTRAINT `fk_wms_outbound_inventory` FOREIGN KEY (`inventory_id`) REFERENCES `wms_inventory` (`id`),
  CONSTRAINT `fk_wms_outbound_user` FOREIGN KEY (`user_id`) REFERENCES `sys_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='领出记录表';

SET FOREIGN_KEY_CHECKS = 1;

-- ----------------------------
-- Initial Data
-- ----------------------------
-- Admin user (password: 123456) - Need to use the hash generated by app
-- INSERT INTO `sys_users` (`username`, `password_hash`, `role`) VALUES ('admin', '$2a$14$....', 'Admin');
